Name0 = str(input("Введите Имя,Фамилию:"))
Name1 = str(input("ФИО мамы:"))
Name2 = str(input("ФИО папы:"))
age = int(input("Сколько вам лет?:"))
place = str(input("Где Вы живёте?:"))
print("Ваше имя ,фамилия:", Name0)
print("ФИО мамы:",Name1)
print("ФИО папы:",Name2)
print("Ваш возраст:",age)
print("Вы живёте в:",place)
