v = int(input("Введите месяц:"))
if v == 1: print("January")
elif v == 2: print("February")
elif v == 3: print("March")
elif v == 4: print("April")
elif v == 5: print("May")
elif v == 6: print("June")
elif v == 7: print("July")
elif v == 8: print("August")
elif v == 9: print("September")
elif v == 10: print("October")
elif v == 11: print("November")
elif v == 12: print("December")
else: print("Введено некорректное значение.")
